apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      app: kubia
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - name: nodejs
        image: reg.navercorp.com/k8s_study/kubia:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
